import turtle as t
t.speed(0)
t.bgcolor('black')
t.left(90)
t.forward(60)
t.right(90)
color=('red','blue','green','yellow','cyan','white','brown','violet','indigo')
for i in range(120):
    t.fillcolor(color[i%7])
    t.begin_fill()
    t.pencolor('black')
    t.forward(i)
    t.right(12)
    t.forward(i)
    t.circle(-40,50)
    t.right(30)
    t.left(30)
    t.right(30)
    t.backward(i)
    t.left(400)
    t.end_fill()
t.done()